Repository mainmatter/qunit-dom, pull requests merged in 2018-07, with the labels that each got.

#95 Update `fsevents` subdependency
  yarn.lock
Labels: internal

#96 Use TypeScript instead of Babel
  .gitignore
  lib/__tests__/does-not-exist.ts
  lib/__tests__/does-not-have-attribute.ts
  lib/__tests__/does-not-have-class.ts
  lib/__tests__/does-not-include-text.ts
  lib/__tests__/exists.ts
  lib/__tests__/has-any-text.ts
  lib/__tests__/has-any-value.ts
  lib/__tests__/has-attribute.ts
  lib/__tests__/has-class.ts
  lib/__tests__/has-no-value.ts
  lib/__tests__/has-text-regex.ts
  lib/__tests__/has-text.ts
  lib/__tests__/has-value.ts
  lib/__tests__/includes-text.ts
  lib/__tests__/is-checked.ts
  lib/__tests__/is-disabled.ts
  lib/__tests__/is-focused.ts
  lib/__tests__/is-not-checked.ts
  lib/__tests__/is-not-disabled.ts
  lib/__tests__/is-not-focused.ts
  lib/__tests__/is-not-required.ts
  lib/__tests__/is-not-visible.ts
  lib/__tests__/is-required.ts
  lib/__tests__/is-visible.ts
  lib/assertions.ts
  lib/assertions/exists.ts
  lib/assertions/focused.ts
  lib/assertions/is-checked.ts
  lib/assertions/is-disabled.ts
  lib/assertions/is-not-checked.ts
  lib/assertions/is-not-required.ts
  lib/assertions/is-not-visible.ts
  lib/assertions/is-required.ts
  lib/assertions/is-visible.ts
  lib/assertions/not-focused.ts
  lib/helpers/collapse-whitespace.test.ts
  lib/helpers/collapse-whitespace.ts
  lib/helpers/element-to-string.test.ts
  lib/helpers/element-to-string.ts
  lib/helpers/test-assertions.ts
  lib/helpers/visible.ts
  lib/qunit-dom.js
  lib/qunit-dom.ts
  package.json
  rollup.config.js
  tsconfig.json
  yarn.lock
Labels: enhancement

#101 Update `.npmignore` file
  .npmignore
Labels: bug

#105 Collapse whitespace for `includesText` assertion
  lib/__tests__/includes-text.ts
  lib/assertions.ts
Labels: breaking
