Repository mainmatter/qunit-dom, pull requests merged in 2018-03, with the labels that each got.

#58 Update `jest` to v21.2.1
  package.json
  yarn.lock
Labels: internal

#62 Add isDisabled() assertion
  lib/__tests__/is-disabled.js
  lib/assertions.js
Labels: enhancement

#60 Allow calling `assert.dom()` with no argument defaulting to `rootElement`
  API.md
  lib/qunit-dom.js
  tests/acceptance/qunit-dom-test.js
Labels: enhancement

#59 Add helpful error for invalid attributes to hasText
  lib/__tests__/has-text.js
  lib/assertions.js
Labels: bug

#63 Add isChecked and isNotChecked assertions
  lib/__tests__/is-checked.js
  lib/__tests__/is-not-checked.js
  lib/assertions.js
  lib/assertions/is-checked.js
  lib/assertions/is-not-checked.js
Labels: enhancement

#64 Add hasAnyText() assertion
  API.md
  lib/__tests__/has-any-text.js
  lib/assertions.js
Labels: enhancement

#65 Add isRequired and isNotRequired assertions
  API.md
  lib/__tests__/is-not-required.js
  lib/__tests__/is-required.js
  lib/assertions.js
  lib/assertions/is-not-required.js
  lib/assertions/is-required.js
Labels: enhancement

#69 Adding new alias for hasText called matchesText
  lib/assertions.js
Labels: enhancement
