Repository mainmatter/qunit-dom, pull requests merged in 2018-04, with the labels that each got.

#74 Add isNotDisabled assertion
  API.md
  lib/__tests__/is-not-disabled.js
  lib/assertions.js
  lib/assertions/is-not-disabled.js
Labels: bug

#66 Add table of contents to API docs
  API.md
  documentation.yml
  lib/assertions.js
  package.json
Labels: documentation

#85 Add API docs for `isDisabled()` assertion
  API.md
  documentation.yml
  lib/assertions.js
Labels: documentation

#86 Documentation cleanup
  lib/assertions.js
Labels: documentation

#87 Merge `isDisabled` and `isNotDisabled` helpers
  lib/__tests__/is-disabled.js
  lib/assertions.js
  lib/assertions/is-disabled.js
  lib/assertions/is-not-disabled.js
Labels: internal
