Repository mainmatter/qunit-dom, pull requests merged in 2019-11, with the labels that each got.

#530 Update Changelog
  CHANGELOG.md
Labels: documentation

#535 isChecked: Add support for `aria-checked="true/false"`
  lib/__tests__/is-checked.ts
  lib/__tests__/is-not-checked.ts
  lib/assertions.ts
  lib/assertions/is-checked.ts
  lib/assertions/is-not-checked.ts
Labels: enhancement

#538 Adjust ignore files
  .gitignore
  .npmignore
Labels: internal

#531 Add `doesNotHaveStyle` assertion
  API.md
  lib/__tests__/does-not-have-style.ts
  lib/assertions.ts
Labels: enhancement

#542 Fix embroider compatibility
  index.js
  vendor/dummy-module.js
Labels: enhancement
