Repository mainmatter/qunit-dom, pull requests merged in 2019-01, with the labels that each got.

#233 helpers/node-list: Add missing `@private` declaration
  lib/helpers/node-list.ts
Labels: documentation

#232 Implement a `hasPseudoElementStyle` assertion
  API.md
  lib/__tests__/has-pseudo-element-style.ts
  lib/assertions.ts
  tests/acceptance/qunit-dom-test.js
  tests/dummy/app/templates/application.hbs
Labels: enhancement

#234 Use ESLint and prettier
  .eslintignore
  .eslintrc.js
  .gitignore
  .prettierrc.js
  .travis.yml
  lib/.eslintrc.js
  lib/__tests__/does-not-exist.ts
  lib/__tests__/does-not-have-attribute.ts
  lib/__tests__/does-not-have-class.ts
  lib/__tests__/does-not-include-text.ts
  lib/__tests__/exists.ts
  lib/__tests__/has-any-text.ts
  lib/__tests__/has-any-value.ts
  lib/__tests__/has-attribute.ts
  lib/__tests__/has-class.ts
  lib/__tests__/has-no-value.ts
  lib/__tests__/has-pseudo-element-style.ts
  lib/__tests__/has-style.ts
  lib/__tests__/has-text-regex.ts
  lib/__tests__/has-text.ts
  lib/__tests__/has-value.ts
  lib/__tests__/includes-text.ts
  lib/__tests__/is-checked.ts
  lib/__tests__/is-disabled.ts
  lib/__tests__/is-focused.ts
  lib/__tests__/is-not-checked.ts
  lib/__tests__/is-not-disabled.ts
  lib/__tests__/is-not-focused.ts
  lib/__tests__/is-not-required.ts
  lib/__tests__/is-not-visible.ts
  lib/__tests__/is-required.ts
  lib/__tests__/is-visible.ts
  lib/assertions.ts
  lib/assertions/exists.ts
  lib/assertions/is-disabled.ts
  lib/assertions/is-not-required.ts
  lib/assertions/is-required.ts
  lib/assertions/is-visible.ts
  lib/helpers/element-to-string.ts
  lib/helpers/node-list.ts
  lib/helpers/test-assertions.ts
  lib/qunit-dom.ts
  package.json
  testem.js
  tests/.eslintrc.js
  tests/acceptance/qunit-dom-test.js
  tests/dummy/app/app.js
  tests/dummy/app/router.js
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  tests/helpers/module-for-acceptance.js
  tests/helpers/resolver.js
  yarn.lock
Labels: internal

#208 Add `matchesSelector()` assertions
  API.md
  lib/__tests__/does-not-match-selector.ts
  lib/__tests__/matches-selector.ts
  lib/assertions.ts
  lib/assertions/matches-selector.ts
Labels: enhancement
