Repository mainmatter/qunit-dom, pull requests merged in 2020-02, with the labels that each got.

#587 TypeScript: Turn on `noImplicityAny` and fix a few type signatures
  lib/__tests__/does-not-exist.ts
  lib/__tests__/does-not-have-attribute.ts
  lib/__tests__/does-not-have-class.ts
  lib/__tests__/does-not-have-style.ts
  lib/__tests__/does-not-have-tagname.ts
  lib/__tests__/does-not-include-text.ts
  lib/__tests__/does-not-match-selector.ts
  lib/__tests__/exists.ts
  lib/__tests__/has-any-text.ts
  lib/__tests__/has-any-value.ts
  lib/__tests__/has-attribute.ts
  lib/__tests__/has-class.ts
  lib/__tests__/has-no-text.ts
  lib/__tests__/has-no-value.ts
  lib/__tests__/has-pseudo-element-style.ts
  lib/__tests__/has-style.ts
  lib/__tests__/has-tagname.ts
  lib/__tests__/has-text-regex.ts
  lib/__tests__/has-text.ts
  lib/__tests__/has-value.ts
  lib/__tests__/includes-text.ts
  lib/__tests__/is-checked.ts
  lib/__tests__/is-disabled.ts
  lib/__tests__/is-focused.ts
  lib/__tests__/is-not-checked.ts
  lib/__tests__/is-not-disabled.ts
  lib/__tests__/is-not-focused.ts
  lib/__tests__/is-not-required.ts
  lib/__tests__/is-not-visible.ts
  lib/__tests__/is-required.ts
  lib/__tests__/is-visible.ts
  lib/__tests__/matches-selector.ts
  lib/assertions.ts
  lib/assertions/exists.ts
  lib/assertions/focused.ts
  lib/assertions/is-checked.ts
  lib/assertions/is-disabled.ts
  lib/assertions/is-not-checked.ts
  lib/assertions/is-not-required.ts
  lib/assertions/is-required.ts
  lib/assertions/is-visible.ts
  lib/assertions/not-focused.ts
  lib/helpers/collapse-whitespace.ts
  lib/helpers/element-to-string.ts
  lib/helpers/test-assertions.ts
  lib/helpers/visible.ts
  tsconfig.json
Labels: internal

#608 hasStyle: Throw an error if expectation object is empty
  lib/__tests__/does-not-have-style.ts
  lib/__tests__/has-style.ts
  lib/assertions.ts
Labels: enhancement

#609 Implement `hasProperty()` assertion
  lib/__tests__/has-property.ts
  lib/assertions.ts
Labels: enhancement

#610 Add support for assertion chaining
  lib/__tests__/does-not-exist.ts
  lib/__tests__/does-not-have-attribute.ts
  lib/__tests__/does-not-have-class.ts
  lib/__tests__/does-not-have-style.ts
  lib/__tests__/does-not-have-tagname.ts
  lib/__tests__/does-not-include-text.ts
  lib/__tests__/does-not-match-selector.ts
  lib/__tests__/exists.ts
  lib/__tests__/has-any-text.ts
  lib/__tests__/has-any-value.ts
  lib/__tests__/has-attribute.ts
  lib/__tests__/has-class.ts
  lib/__tests__/has-no-text.ts
  lib/__tests__/has-no-value.ts
  lib/__tests__/has-property.ts
  lib/__tests__/has-style.ts
  lib/__tests__/has-tagname.ts
  lib/__tests__/has-text.ts
  lib/__tests__/has-value.ts
  lib/__tests__/includes-text.ts
  lib/__tests__/is-checked.ts
  lib/__tests__/is-disabled.ts
  lib/__tests__/is-focused.ts
  lib/__tests__/is-not-checked.ts
  lib/__tests__/is-not-disabled.ts
  lib/__tests__/is-not-focused.ts
  lib/__tests__/is-not-required.ts
  lib/__tests__/is-not-visible.ts
  lib/__tests__/is-required.ts
  lib/__tests__/is-visible.ts
  lib/__tests__/matches-selector.ts
  lib/assertions.ts
Labels: enhancement

#614 Fix example for hasProperty
  lib/assertions.ts
Labels: documentation

#619 Add GitHub Actions config
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: internal
