Repository mainmatter/qunit-dom, pull requests merged in 2021-12, with the labels that each got.

#1348 Update Build Status badge: Travis -> GH Actions
  README.md
Labels: documentation

#1360 CI: Add Ember 3.28 scenario
  .github/workflows/ci.yml
  tests/dummy/config/ember-try.js
Labels: internal

#1361 Use `pnpm` package manager
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .npmignore
  .pnpm-debug.log
  CONTRIBUTING.md
  RELEASE.md
  package.json
  pnpm-lock.yaml
  renovate.json
  tests/dummy/config/ember-try.js
  yarn.lock
Labels: internal

#1365 Ember.js: Declare `octane` edition compatibility
  package.json
  tests/dummy/config/optional-features.json
Labels: internal

#1384 Run pnpm upgrade
  package.json
  pnpm-lock.yaml
Labels: dependencies
