Repository mainmatter/qunit-dom, pull requests merged in 2023-10, with the labels that each got.

#2031 Drop ember qunit less than v6
  .github/workflows/ci.yml
  README.md
  index.js
  package.json
  pnpm-lock.yaml
  tests/dummy/config/ember-try.js
  tests/test-helper.js
  vendor/dummy-module.js
  vendor/overwrite-qunit-dom-root-element.js
Labels: breaking

#2055 chore(release): copy static LICENSE and README into the package during build
  LICENSE
  README.md
  packages/qunit-dom/.gitignore
  packages/qunit-dom/package.json
  packages/qunit-dom/rollup.config.mjs
  pnpm-lock.yaml
Labels: internal

#2060 chore(deps): bump prettier and eslint-plugin-prettier
  packages/qunit-dom/package.json
  packages/test-app/package.json
  packages/test-app/tests/acceptance/qunit-dom-test.js
  pnpm-lock.yaml
Labels: dependencies

#2061 chore(ci): use volta-cli github action for node and pnpm setup
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: internal

#2066 Switch to Vitest because it supports ESM
  .github/workflows/ci.yml
  packages/qunit-dom/.eslintrc.cjs
  packages/qunit-dom/lib/__tests__/does-not-exist.ts
  packages/qunit-dom/lib/__tests__/does-not-have-attribute.ts
  packages/qunit-dom/lib/__tests__/does-not-have-class.ts
  packages/qunit-dom/lib/__tests__/does-not-have-style.ts
  packages/qunit-dom/lib/__tests__/does-not-have-tagname.ts
  packages/qunit-dom/lib/__tests__/does-not-include-text.ts
  packages/qunit-dom/lib/__tests__/does-not-match-selector.ts
  packages/qunit-dom/lib/__tests__/exists.ts
  packages/qunit-dom/lib/__tests__/has-any-text.ts
  packages/qunit-dom/lib/__tests__/has-any-value.ts
  packages/qunit-dom/lib/__tests__/has-aria.ts
  packages/qunit-dom/lib/__tests__/has-attribute.ts
  packages/qunit-dom/lib/__tests__/has-class.ts
  packages/qunit-dom/lib/__tests__/has-no-text.ts
  packages/qunit-dom/lib/__tests__/has-no-value.ts
  packages/qunit-dom/lib/__tests__/has-property.ts
  packages/qunit-dom/lib/__tests__/has-pseudo-element-style.ts
  packages/qunit-dom/lib/__tests__/has-style.ts
  packages/qunit-dom/lib/__tests__/has-tagname.ts
  packages/qunit-dom/lib/__tests__/has-text-regex.ts
  packages/qunit-dom/lib/__tests__/has-text.ts
  packages/qunit-dom/lib/__tests__/has-value.ts
  packages/qunit-dom/lib/__tests__/includes-text.ts
  packages/qunit-dom/lib/__tests__/is-checked.ts
  packages/qunit-dom/lib/__tests__/is-disabled.ts
  packages/qunit-dom/lib/__tests__/is-focused.ts
  packages/qunit-dom/lib/__tests__/is-not-checked.ts
  packages/qunit-dom/lib/__tests__/is-not-disabled.ts
  packages/qunit-dom/lib/__tests__/is-not-focused.ts
  packages/qunit-dom/lib/__tests__/is-not-required.ts
  packages/qunit-dom/lib/__tests__/is-not-valid.ts
  packages/qunit-dom/lib/__tests__/is-not-visible.ts
  packages/qunit-dom/lib/__tests__/is-required.ts
  packages/qunit-dom/lib/__tests__/is-valid.ts
  packages/qunit-dom/lib/__tests__/is-visible.ts
  packages/qunit-dom/lib/__tests__/matches-selector.ts
  packages/qunit-dom/lib/helpers/__tests__/node-list.ts
  packages/qunit-dom/lib/helpers/collapse-whitespace.test.ts
  packages/qunit-dom/lib/helpers/element-to-string.test.ts
  packages/qunit-dom/package.json
  packages/qunit-dom/vitest.config.ts
  pnpm-lock.yaml
Labels: internal
