Repository mainmatter/qunit-dom, pull requests merged in 2024-04, with the labels that each got.

#2100 chore(deps): bump release-it-changelog to 6.1.0
  packages/qunit-dom/.release-it.cjs
  packages/qunit-dom/package.json
  pnpm-lock.yaml
Labels: dependencies

#2090 Support ShadowRoot, add tests for rootElement, fixes #2089
  API.md
  packages/qunit-dom/lib/__tests__/root-element.ts
  packages/qunit-dom/lib/assertions.ts
  packages/qunit-dom/lib/helpers/test-assertions.ts
  packages/qunit-dom/lib/install.ts
Labels: bug

#2080 remove hidden target override from compilerOptions
  packages/qunit-dom/tsconfig.json
Labels: internal

#2105 fix(hasStyle): allow using camelCase properties inside assertion object
  packages/qunit-dom/lib/__tests__/has-style.ts
  packages/qunit-dom/lib/assertions.ts
Labels: bug
